<?php

use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\I18N;

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), $title]]) ?>

<h1><?= $title ?></h1>

<form method="post" name="jc-simple-footer" class="form-horizontal">
    <?= csrf_field() ?>
    <div class="row mb-3">
        <label for="footer-text" class="col-sm-3 col-form-label">
            <?= I18N::translate('Footer') ?>
        </label>
        <div class="col-sm-9">
            <input type="text" class="form-control" name="footer-text" id="footer-text" value="<?= e($footer_text) ?>">
            <div class="form-text">
                <?= I18N::translate('Leave the page title and text blank if you only want an additional footer to add your credits or copyright, for example.') ?>
            </div>
        </div>
    </div>

    <div class="row mb-3">
        <label for="page-title" class="col-sm-3 col-form-label">
            <?= I18N::translate('Page title') ?>
        </label>
        <div class="col-sm-9">
            <input type="text" class="form-control" name="page-title" id="page-title"
                value="<?= e($page_title) ?>">
        </div>
    </div>

    <div class="row mb-3">
        <label for="page-body" class="col-sm-3 col-form-label">
            <?= I18N::translate('Page text') ?>
        </label>
        <div class="col-sm-9">
            <textarea name="page-body" id="page-body" class="form-control html-edit" rows="10"><?= e($page_body) ?></textarea>
        </div>
    </div>

    <div class="row mb-3">
        <div class="offset-sm-3 col-sm-9">
            <button type="submit" class="btn btn-primary">
                <?= view('icons/save') ?>
                <?= I18N::translate('save') ?>
            </button>
        </div>
    </div>
</form>
