<?php

use Fisharebest\Webtrees\I18N;

?>

<div class="jc-simple-footer-page">
    <?php if ($is_admin) : ?>
        <div class="jc-simple-footer-page-edit text-end">
            <a href="<?= e(route('module', ['module' => $module, 'action' => 'Admin'])) ?>">
                <?= I18N::translate('Edit') ?>
            </a>
        </div>
    <?php endif ?>
    <h2 class="wt-page-title jc-simple-footer-page-title"><?= $page_title ?></h2>
    <div class="jc-simple-footer-page-body"><?= $page_body ?></div>
</div>
